### ISSUE TITLE
Crash immediately on application start

### ISSUE THREAD

**Issue by ZaraPhu** [Turnip-Labs/babric-instance-repo#2]
The application crashes immediately after it starts, and throws an error message.

For background, I'm using an early 2015 model Macbook Air on its latest update macOS Monterey 12.7.3. I'm on the latest Java update that's available for me to install: Java 8 Update 401. I've re-checked these and they're as up-to-date as I can get them. 

**The console spits out the following log:**
MultiMC version: 0.7.0-3814

Launched instance in online mode

authserver.mojang.com resolves to:
    [18.245.96.19, 18.245.96.43, 18.245.96.114, 18.245.96.50]

session.minecraft.net resolves to:
    [2620:1ec:46::35, 2620:1ec:bdf::35, 13.107.213.35, 13.107.246.35]

textures.minecraft.net resolves to:
    [2620:1ec:46::35, 2620:1ec:bdf::35, 13.107.213.35, 13.107.246.35]

api.mojang.com resolves to:
    [2620:1ec:bdf::35, 2620:1ec:46::35, 13.107.213.35, 13.107.246.35]

Minecraft folder is:
/Users/zaraphukan/Desktop/MultiMC.app/Data/instances/bta_babric_instance_7.1pre1a/.minecraft

Java path is:
/usr/bin/java

Checking Java version...
Java is version 1.8.0_401, using 64-bit architecture, from Oracle Corporation.

Main Class:
  net.fabricmc.loader.impl.launch.knot.KnotClient

Native path:
  /Users/zaraphukan/Desktop/MultiMC.app/Data/instances/bta_babric_instance_7.1pre1a/natives

Traits:
traits texturepacks
traits noapplet
traits legacyLaunch

Libraries:
  /Users/zaraphukan/Desktop/MultiMC.app/Data/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  /Users/zaraphukan/Desktop/MultiMC.app/Data/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  /Users/zaraphukan/Desktop/MultiMC.app/Data/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-babric.1/lwjgl-2.9.4-babric.1.jar
  /Users/zaraphukan/Desktop/MultiMC.app/Data/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-babric.1/lwjgl_util-2.9.4-babric.1.jar
  /Users/zaraphukan/Desktop/MultiMC.app/Data/libraries/babric/log4j-config/1.0.0/log4j-config-1.0.0.jar
  /Users/zaraphukan/Desktop/MultiMC.app/Data/libraries/net/minecrell/terminalconsoleappender/1.2.0/terminalconsoleappender-1.2.0.jar
  /Users/zaraphukan/Desktop/MultiMC.app/Data/libraries/org/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.8.0-beta4.jar
  /Users/zaraphukan/Desktop/MultiMC.app/Data/libraries/org/apache/logging/log4j/log4j-slf4j18-impl/2.16.0/log4j-slf4j18-impl-2.16.0.jar
  /Users/zaraphukan/Desktop/MultiMC.app/Data/libraries/org/apache/logging/log4j/log4j-api/2.16.0/log4j-api-2.16.0.jar
  /Users/zaraphukan/Desktop/MultiMC.app/Data/libraries/org/apache/logging/log4j/log4j-core/2.16.0/log4j-core-2.16.0.jar
  /Users/zaraphukan/Desktop/MultiMC.app/Data/libraries/com/google/code/gson/gson/2.10.1/gson-2.10.1.jar
  /Users/zaraphukan/Desktop/MultiMC.app/Data/libraries/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.jar
  /Users/zaraphukan/Desktop/MultiMC.app/Data/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
  /Users/zaraphukan/Desktop/MultiMC.app/Data/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
  /Users/zaraphukan/Desktop/MultiMC.app/Data/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
  /Users/zaraphukan/Desktop/MultiMC.app/Data/libraries/net/fabricmc/tiny-mappings-parser/0.3.0+build.17/tiny-mappings-parser-0.3.0+build.17.jar
  /Users/zaraphukan/Desktop/MultiMC.app/Data/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar
  /Users/zaraphukan/Desktop/MultiMC.app/Data/libraries/net/fabricmc/tiny-remapper/0.8.2/tiny-remapper-0.8.2.jar
  /Users/zaraphukan/Desktop/MultiMC.app/Data/libraries/net/fabricmc/access-widener/2.1.0/access-widener-2.1.0.jar
  /Users/zaraphukan/Desktop/MultiMC.app/Data/libraries/org/ow2/asm/asm/9.3/asm-9.3.jar
  /Users/zaraphukan/Desktop/MultiMC.app/Data/libraries/org/ow2/asm/asm-analysis/9.3/asm-analysis-9.3.jar
  /Users/zaraphukan/Desktop/MultiMC.app/Data/libraries/org/ow2/asm/asm-commons/9.3/asm-commons-9.3.jar
  /Users/zaraphukan/Desktop/MultiMC.app/Data/libraries/org/ow2/asm/asm-tree/9.3/asm-tree-9.3.jar
  /Users/zaraphukan/Desktop/MultiMC.app/Data/libraries/org/ow2/asm/asm-util/9.3/asm-util-9.3.jar
  /Users/zaraphukan/Desktop/MultiMC.app/Data/instances/bta_babric_instance_7.1pre1a/libraries/fabric-loader-0.14.19-babric.3-bta.jar
  /Users/zaraphukan/Desktop/MultiMC.app/Data/instances/bta_babric_instance_7.1pre1a/.minecraft/bin/minecraft.jar

Native libraries:
  /Users/zaraphukan/Desktop/MultiMC.app/Data/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-osx.jar
  /Users/zaraphukan/Desktop/MultiMC.app/Data/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-babric.1/lwjgl-platform-2.9.4-babric.1-natives-osx.jar

Mods:
  [✔️] halplibe-3.2.1.jar
  [✔️] modmenu-bta-2.0.3.jar

Jar Mods:
  Better than Adventure! (bta.jar)

Params:
  --username ZaraOctavia --session token:<ACCESS TOKEN>:<PROFILE ID> --gameDir /Users/zaraphukan/Desktop/MultiMC.app/Data/instances/bta_babric_instance_7.1pre1a/.minecraft --assetsDir /Users/zaraphukan/Desktop/MultiMC.app/Data/instances/bta_babric_instance_7.1pre1a/.minecraft/resources --server beta.windowslogic.co.uk --port 25566

Window size: max (if available)

Java Arguments:
[-Dfml.ignoreInvalidMinecraftCertificates=true, -Dfml.ignorePatchDiscrepancies=true, -Xdock:icon=icon.png, -Xdock:name="MultiMC: bta_babric_instance_7.1pre1a", -Xms512m, -Xmx1024m, -Duser.language=en]

Minecraft process ID: 2754

Using onesix launcher.

Could not find Minecraft path field.
ScriptEngineManager providers.next(): javax.script.ScriptEngineFactory: Provider jdk.nashorn.api.scripting.NashornScriptEngineFactory not found
[14:57:19] [main/INFO] (FabricLoader/GameProvider) Loading Minecraft 7.1 Prerelease 1a with Fabric Loader 0.14.19-babric.3-bta
[14:57:19] [main/INFO] (FabricLoader/Mappings) Mappings not present!
[14:57:19] [main/INFO] (FabricLoader) Loading 6 mods:
	- fabricloader 0.14.19-babric.3-bta+local
	- halplibe 3.2.1
	   \-- org_apache_commons_commons-lang3 3.12.0
	- java 8
	- minecraft 7.1-beta.1a
	- modmenu 2.0.3
[14:57:19] [main/INFO] (FabricLoader/Mixin) SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/Users/zaraphukan/Desktop/MultiMC.app/Data/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[14:57:20] [main/INFO] (halplibe) Config file name: halplibe.cfg
[14:57:20] [main/INFO] (halplibe) Config file path: /Users/zaraphukan/Desktop/MultiMC.app/Data/instances/bta_babric_instance_7.1pre1a/.minecraft/config/halplibe.cfg
0 Achievements
[14:57:21] [main/INFO] (halplibe) HalpLibe initialized.
[14:57:21] [Client-Main/INFO] (halplibe) Successfully registered packet turniplabs.halplibe.util.version.PacketModList with id 26
[14:57:21] [Client-Main/INFO] (halplibe) Successfully registered packet turniplabs.halplibe.util.network.PacketExtendedMobSpawn with id 36
[14:57:22] [Client-Main] 1870 Translation Keys
[14:57:22] [Client-Main] Skipping bad option: shaderOverride:
[14:57:22] [Client-Main] Skipping bad option: lastServer:
[14:57:22] [Client-Main] Skipping bad option: selectedController:
[14:57:22] [Client-Main] Skipping bad option: key_key.autoWalk:
[14:57:22] [Client-Main] Skipping bad option: key_key.sprint:
[14:57:22] [Client-Main] Resolution: 854 x 480
[14:57:22] [Client-Main] Java Version: 1.8.0_401

A fatal error has been detected by the Java Runtime Environment:

SIGILL (0x4) at pc=0x00007ff804b2d474, pid=2754, tid=0x0000000000003917

JRE version: Java(TM) SE Runtime Environment (8.0_401) (build 1.8.0_401-b10)
Java VM: Java HotSpot(TM) 64-Bit Server VM (25.401-b10 mixed mode bsd-amd64 compressed oops)
Problematic frame:
C  [AppKit+0x383474]  -[NSOpenGLContext setView:]+0xbd

Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again

An error report file with more information is saved as:
/Users/zaraphukan/Desktop/MultiMC.app/Data/instances/bta_babric_instance_7.1pre1a/.minecraft/hs_err_pid2754.log

If you would like to submit a bug report, please visit:
  http://bugreport.java.com/bugreport/crash.jsp
The crash happened outside the Java Virtual Machine in native code.
See problematic frame for where to report the bug.

Process crashed with exit code 6 (0x6).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.
Clipboard copy at: 30 Jan 2024 14:57:30 -0500

**Comment by ZaraPhu** [comment]
Managed to install JDK 21, but the error persists in a different form. The application still crashed at runtime, but now a window opens and shows the following error:

A mod crashed on startup!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'halplibe'!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:164)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.multimc.onesix.OneSixLauncher.legacyLaunch(OneSixLauncher.java:164)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:273)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'halplibe'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162)
	... 8 more
Caused by: java.lang.ExceptionInInitializerError
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:534)
	at java.base/java.lang.Class.forName(Class.java:513)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 10 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.core.block.Block failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:421)
	at java.base/java.lang.Class.forName(Class.java:412)
	at turniplabs.halplibe.HalpLibe.<clinit>(HalpLibe.java:47)
	... 17 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 25 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinPreProcessorException: Attach error for halplibe.mixins.json:mixins.registry.BlockMixin from mod halplibe during activity: [Transform -> Method addInfo(Ljava/lang/String;ILnet/minecraft/core/block/material/Material;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> INVOKESPECIAL -> java/lang/StringBuilder::<init>:()V]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:313)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 28 more
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: java.lang.StringBuilder
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMemberReference(MixinPreProcessorStandard.java:783)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMethod(MixinPreProcessorStandard.java:769)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:735)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:307)
	... 34 more
Caused by: java.lang.ClassNotFoundException: java.lang.StringBuilder
	... 38 more

**Comment by MartinSVK12** [comment]
You should update the mods in the instance, also try other Java vendors like https://adoptium.net/temurin/releases/?version=8&os=mac&arch=any for example.

**Comment by MartinSVK12** [comment]
If you're still having problems, update to the latest BTA version and update all the mods in the instance and try other Java vendors like https://adoptium.net/temurin/releases/?version=8&os=mac&arch=any for example.
